services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: elekto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d elekto']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '5001:5000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
